config/routes.rb
PickingDucks::Application.routes.draw do
  resources :sessions
  resources :events
  resources :bets 
  resources :users 
  resources :events do
    resources :bets
  end
  resources :password_resets
  resources :cashouts
  
  get "/how_to_play" => "application#how_to_play", :as => "how_to_play"
  get "/privacy" => "application#privacy", :as => "privacy"
  get "/terms_of_service" => "application#terms_of_service", :as => "terms_of_service"
  get "/about_us" => "application#about_us", :as => "about_us"
  
  get 'public_profile/:id' => "users#public_profile", :as => "public_profile"
  get 'pay_for_bet/:user_id/:bet_id' => "users#pay_for_bet", :as => "pay_for_bet"
  get 'pay_money_for_bet/:user_id/:bet_id' => "users#pay_money_for_bet", :as => "pay_money_for_bet"
  
  get "/sport/:sport_id" => "sports#sport_home", :as => "sport_home"
  
  get "/bets_home" => "bets#bets_home", :as => "bets_home"
  get "/make_parlay" => "bets#make_parlay", :as => "make_parlay"
  get "/request_cashout" => "users#request_cashout", :as => "request_cashout"
  get "/get_bets_for_date" => "users#get_bets_for_date", :as => "get_bets_for_date"
  get '/calc_payout/:event_id/:amount/:pick' => "bets#calc_payout", :as => "calc_payout"
  get '/reset_ducks' => 'users#reset_ducks', :as => "reset_ducks"
  post "/add_bets_to_parlay" => "bets#add_bets_to_parlay", :as => "add_bets_to_parlay"
  post '/make_bet_private/:id' => "bets#make_bet_private", :as => "make_bet_private"
  post '/buy_ducks' => "users#buy_duck", :as => "buy_ducks"
  post '/buy_bet_info' => "users#buy_bet_info", :as => "buy_bet_info"
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "user#new", :as => "sign_up"
  get "get_featured" => "home#get_featured", :as => "get_featured"
  root :to => "home#index"

end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_many :purchases
  
  attr_accessible :amount, :bet_home, :over_under, :bet_type, :sport, :event_id, :user_id, :parlay, :parlay_id, :pending, :winning, :closed_at, :resulting_bankroll, :public, :money_price
  
  validates :amount, :numericality => {:greater_than => 0}
  validates_presence_of :bet_type
  
  scope :get_pending, where(:pending => true) 

  def payout

  end 
  
  def won(event_obj, home_score, away_score)
    puts "home score #{event_obj.home_team}: " + home_score.to_s
    puts "away score #{event_obj.away_team}: " + away_score.to_s    
     
    case bet_type
      when "home"
        case event_obj.sport
          when 1
            if home_score + event_obj.spread > away_score 
              return true
            end
          when 2
            if home_score + event_obj.spread > away_score 
              return true
            end
          when 3
            if home_score > away_score
            return true
          end
          when 4
        end        
      when "away"
        case event_obj.sport
          when 1
            if home_score + event_obj.spread < away_score 
              return true
            end
          when 2
            if home_score + event_obj.spread < away_score 
              return true
            end
          when 3
            if away_score > home_score
              return true
            end
          when 4
        end
      when "over"
        if home_score + away_score > event_obj.total_points
          return true
        end
      when "under"
        if home_score + away_score < event_obj.total_points
          return true
        end
    end
    false 
  end
  
  def self.close_bets
    nfl_game_url = "http://sportscaster.xmlteam.com/gateway/php_ci/searchEvents.php?league-keys=l.nfl.com&date-offset=-1&date-offset-span=2&date-offset-midnight=1600&sort-order=asc&publisher-keys=sportsnetwork.com&max-result-count=200&content-returned=metadata-and-scores&content-format=sportsml&rendering-engine=mvc-view&gateway-theme=default&query-debug=false"
    nba_game_url = "http://sportscaster.xmlteam.com/gateway/php_ci/searchEvents.php?league-keys=l.nba.com&date-offset=-1&date-offset-span=2&date-offset-midnight=1600&sort-order=asc&publisher-keys=sportsnetwork.com&max-result-count=200&content-returned=metadata-and-scores&content-format=sportsml&rendering-engine=mvc-view&gateway-theme=default&query-debug=false"
    mlb_game_url = "http://sportscaster.xmlteam.com/gateway/php_ci/searchEvents.php?league-keys=l.mlb.com&date-offset=-1&date-offset-span=2&date-offset-midnight=1600&sort-order=asc&publisher-keys=sportsnetwork.com&max-result-count=200&content-returned=metadata-and-scores&content-format=sportsml&rendering-engine=mvc-view&gateway-theme=default&query-debug=false"
    nhl_game_url = ""

    xml_doc = Nokogiri::XML(open(nfl_game_url, :http_basic_authentication => ["prosperitech", "l1v3l0ng"]))
    xml_doc.xpath('//sports-event').each do |event_xml|      
      event_obj = Event.find_by_extern_id(event_xml.xpath('./event-metadata/@event-key').to_s)
      if !event_obj.nil? && event_xml.xpath("./team/team-metadata[@alignment='home']/../team-stats/@event-outcome").to_s != "undecided" 
         event_obj.finished = true
         event_obj.save
        bets_for_event = Bet.where(:event_id => event_obj.id, :pending => true)
        if bets_for_event.length > 0
          bets_for_event.each do |bet|       
              user = bet.user  
              event_obj.home_total = event_xml.xpath("./team/team-metadata[@alignment='home']/../team-stats/@score").to_s.to_i
              event_obj.away_total = event_xml.xpath("./team/team-metadata[@alignment='away']/../team-stats/@score").to_s.to_i
              event_obj.save          
              if bet.won(event_obj, event_obj.home_total, event_obj.away_total)
                
                user.wins += 1
                user.assign_win_percentage
                case bet.sport
                when 1
                  user.nfl_wins += 1
                  user.bankroll += bet.amount 
                  user.available_bankroll += bet.amount + bet.amount
                  user.assign_nfl_win_percentage              
                end
                user.save
                bet.resulting_bankroll = user.bankroll
                bet.winning = true
              else              
                user.losses += 1
                user.assign_win_percentage
                case bet.sport
                when 1
                  user.nfl_losses += 1
                  user.bankroll -= bet.amount
                  user.assign_nfl_win_percentage              
                end
                user.save
                bet.resulting_bankroll = user.bankroll
                bet.winning = false
              end
              
              bet.pending = false
              bet.closed_at = Time.zone.now.to_date
              
              bet.save
             end
           end
        end
    end

    xml_doc = Nokogiri::XML(open(nba_game_url, :http_basic_authentication => ["prosperitech", "l1v3l0ng"]))
    xml_doc.xpath('//sports-event').each do |event_xml|
      event_obj = Event.find_by_extern_id(event_xml.xpath('./event-metadata/@event-key').to_s)
      if !event_obj.nil? && event_xml.xpath("./team/team-metadata[@alignment='home']/../team-stats/@event-outcome").to_s != "undecided" 
         event_obj.finished = true
         event_obj.save 
        bets_for_event = Bet.where(:event_id => event_obj.id, :pending => true)
        if bets_for_event.length > 0
          bets_for_event.each do |bet|          
              user = bet.user       
              event_obj.home_total = event_xml.xpath("./team/team-metadata[@alignment='home']/../team-stats/@score").to_s.to_i
              event_obj.away_total = event_xml.xpath("./team/team-metadata[@alignment='away']/../team-stats/@score").to_s.to_i
              event_obj.save      
              if bet.won(event_obj, event_obj.home_total, event_obj.away_total)
                
                user.wins += 1
                user.assign_win_percentage
                case bet.sport
                when 2
                  user.nba_wins += 1
                  user.bankroll += bet.amount 
                  user.available_bankroll += bet.amount + bet.amount
                  user.assign_nba_win_percentage              
                end
                user.save
                bet.resulting_bankroll = user.bankroll
                bet.winning = true
              else              
                user.losses += 1
                user.assign_win_percentage
                case bet.sport
                when 2
                  user.nba_losses += 1
                  user.bankroll -= bet.amount
                  user.assign_nba_win_percentage              
                end
                user.save
                bet.resulting_bankroll = user.bankroll
                bet.winning = false
              end
              
              bet.pending = false
              bet.closed_at = Time.zone.now.to_date
              
              bet.save
             end
           end
        end
    end
    

    xml_doc = Nokogiri::XML(open(mlb_game_url, :http_basic_authentication => ["prosperitech", "l1v3l0ng"]))
    xml_doc.xpath('//sports-event').each do |event_xml|
      event_obj = Event.find_by_extern_id(event_xml.xpath('./event-metadata/@event-key').to_s)
      if !event_obj.nil? && event_xml.xpath("./team/team-metadata[@alignment='home']/../team-stats/@event-outcome").to_s != "undecided" 
        event_obj.finished = true
        event_obj.save
     
        bets_for_event = Bet.where(:event_id => event_obj.id, :pending => true)
        if bets_for_event.length > 0
          bets_for_event.each do |bet|        
              user = bet.user     
              event_obj.home_total = event_xml.xpath("./team/team-metadata[@alignment='home']/../team-stats/@score").to_s.to_i
              event_obj.away_total = event_xml.xpath("./team/team-metadata[@alignment='away']/../team-stats/@score").to_s.to_i
              event_obj.save        
              if bet.won(event_obj, event_obj.home_total, event_obj.away_total)
                
                user.wins += 1
                user.assign_win_percentage
                case bet.sport              
                when 3
                  user.mlb_wins += 1
                  if bet.bet_type == "home"
                    if event_obj.moneyline_home > 0
                      user.available_bankroll += bet.amount + bet.amount * event_obj.moneyline_home / 100
                      user.bankroll += bet.amount * event_obj.moneyline_home / 100
                    else 
                      user.available_bankroll += bet.amount + bet.amount * 100 / event_obj.moneyline_home.abs 
                      user.bankroll += bet.amount * 100 / event_obj.moneyline_home.abs 
                    end
                  elsif bet.bet_type == "away"
                    if event_obj.moneyline_away > 0
                      user.available_bankroll += bet.amount + bet.amount * event_obj.moneyline_away / 100
                      user.bankroll += bet.amount * event_obj.moneyline_away / 100
                    else 
                      user.available_bankroll += bet.amount + bet.amount * 100 / event_obj.moneyline_away.abs
                      user.bankroll += bet.amount * 100 / event_obj.moneyline_away.abs 
                    end
                  else
                    user.available_bankroll += bet.amount + bet.amount
                    user.bankroll += bet.amount
                  end
                  user.assign_mlb_win_percentage              
                end
                user.save!
                bet.resulting_bankroll = user.bankroll
                bet.winning = true
              else              
                user.losses += 1

app/controllers/bets_controller.rb
class BetsController < ApplicationController

  def new
    @bet = Bet.new
    @event = Event.find(params[:event_id])    
  end
  
  def create
    @event = Event.find(params[:event_id])    
    
    if params[:bet][:amount].to_i <= current_user.available_bankroll
      bet = Bet.new(params[:bet])
      if bet.save
        current_user.bets << bet        
        current_user.available_bankroll = current_user.available_bankroll - params[:bet][:amount].to_i
        current_user.save
        update_current_user
        @event.bets << bet
        @event.save
        flash.notice = "Your bet has been placed! Good luck!!"
        redirect_to Rails.application.routes.url_helpers.user_path(current_user.id) 
      else       
        flash[:error] = bet.errors.full_messages.collect { |msg| msg + "<br/>" }.join
        @bet = Bet.new
        render :action => 'new'
      end 
    else
      flash[:alert] = "The bet you were attempting to make exceeds your current bankroll of Ducks!"
      redirect_to :action => 'bets_home'
    end  
  end
  
  def edit
    @bet = Bet.find(params[:id])
  end
  
  def update
    @bet = Bet.find(params[:id])
    @bet.money_price = params[:bet][:money_price]
    @bet.save!
    
    redirect_to user_path(current_user)
  end
  
  def add_bets_to_parlay
    parlay = current_user.parlays.build
    parlay.amount = params[:amount]
    parlay.pending = true
    params[:event_id].each do |event|
      bet = parlay.bets.build
      if params[:sport][event][0]
        bet.update_attributes({:event_id => event, :amount => params[:amount], :bet_type => params[:bet_type][event], :sport => params[:sport][event][0], :parlay => true})
      else
        bet.update_attributes({:event_id => event, :amount => params[:amount], :bet_type => params[:bet_type][event], :sport => params[:sport][event][1], :parlay => true})
      end      
    end
    
    if parlay.save
      current_user.save
      update_current_user
      flash[:notice] = "Your parlay bet has been placed!"
      redirect_to '/bets_home'
    else
      flash[:error] = "An error occured while creating your parlay"
      return redirect_to '/bets_home'
    end
    
  end
  
  def bets_home
    @games = Event.where('start_time > ? and start_time < ? and (spread is not null or moneyline_home is not null)', Time.zone.now.to_date, 7.days.from_now.to_date).order("sport ASC")
    @sport = 0
  end
  
  def make_parlay
    @games = Event.where('start_time > ? and start_time < ?', Time.zone.now.to_date, 7.days.from_now.to_date).order("sport ASC")
    @sport = 0 # used to set headers in parlay_select_table
  end
  
  def make_bet_private
    bet = Bet.find(params[:id])
    
    if bet.update_attributes params[:bet]
      if params[:bet][:duck_price]
        flash[:notice] = "Bet has been made purchaseable for #{bet.duck_price} ducks!"        
      else 
        flash[:notice] = "Bet has been made purchaseable for #{bet.money_price} dollars!"     
      end
      redirect_to user_path current_user.id        
    else
      flash[:alert] = "An error occured."
      redirect_to root_path
    end    
  end

  def calc_payout
    render :text => Event.calc_payout(params[:event_id], params[:amount], params[:pick])
  end  

end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_new.html.erb
<h1><%= "#{event.away_team} @ #{event.home_team}" %></h1>
 <div id="bet_tabs"> 	
 	<ul>
 		<li><a href="#handicap">Handicap</a></li>
 		<li><a href="#over_under">Over Under</a></li>
 	</ul>	
 	<div id="handicap"> 	
 		<%= form_for bet, :html => { :id => "handicap_bet_form" } do |f| %>	 
 			
		 <p>
		 	<h3>
		 		<% if event.sport == 3 %>
		 			<%= "This is a moneyline pick: " %>
		 		<% elsif event.spread > 0 %>
		 			The <%= event.home_team %> are favored by <%= event.spread %> points
		 		<% else %>
		 			<%= event.away_team %> are favored by <%= event.spread.abs %> points
		 		<% end %>
		 	</h3>
		 	<%= hidden_field_tag 'event_id', event.id %>
		 	<%= f.hidden_field 'sport', :value => event.sport %>
		 	<%= f.hidden_field 'pending', :value => true %>
		 	<%= f.hidden_field 'parlay', :value => false %>
		 	<% if event.moneyline_home %>
		 		<%= event.home_team %> (<%= event.moneyline_home %>): <%= f.radio_button(:bet_type, 'home', :data => {:team => "#{event.home_team}(#{event.moneyline_home})"}) %><br />
			 	<%= event.away_team %> (<%= event.moneyline_away %>): <%= f.radio_button(:bet_type, 'away', :data => {:team => "#{event.away_team}(#{event.moneyline_away})"}) %>
		 	<% else %>
			 	<%= event.home_team %> (<%= event.spread %>): <%= f.radio_button(:bet_type, 'home', :data => {:team => "#{event.home_team}(#{event.spread})"}) %><br />
			 	<%= event.away_team %> (<%= -event.spread %>): <%= f.radio_button(:bet_type, 'away', :data => {:team => "#{event.away_team}(#{-event.spread})"}) %>
			<% end %><br />
		 	Amount: <%= f.number_field :amount, :min => 1, :class => "number_input" %>
		 </p>
		 <p><%= f.submit 'Place Pick!', :class => 'button place_bet' %></p>
		 <% end %>
	</div>
	<div id="over_under">
		<%= form_for bet, :html => { :id => "over_under_bet_form" }  do |f| %>	 
		 <p>
		 	<h3>
		 		Total Points: <%= event.total_points %>
		 	</h3>
		 	<%= hidden_field_tag 'event_id', event.id %>
		 	<%= f.hidden_field 'sport', :value => event.sport %>
		 	<%= f.hidden_field 'pending', :value => true %>
		 	<%= f.hidden_field 'parlay', :value => false %>
		 	Over: <%= f.radio_button(:bet_type, 'over', :data => {:team => event.home_team, :pick => "over"}) %><br />
		 	Under: <%= f.radio_button(:bet_type, 'under', :data => {:team => event.away_team, :pick => "under"}) %><br/>
		 	Amount: <%= f.number_field :amount, :id => "bet_amount2", :min => 1, :class => "number_input", :data => {:total => event.total_points} %>
		 	<p><%= f.submit 'Place Pick!', :class => 'button place_bet' %></p>
		 </p>
		 <% end %>
	</div>	 
</div>	
<script type="text/javascript">
	$("#bet_tabs").tabs();
	  $("#handicap_bet_form").submit(function (e) {
	  	e.preventDefault();
	  	if ($(this).children('input[name="bet[bet_type]"]:checked').length > 0 && $(this).children('input[type="number"]').val() > 0) {
	  		var payout = 0;
	  		var calc_payout = function () {
	  			jQuery.ajax({
				  dataType: 'html',
				  async: false,
				  url: "/calc_payout/" + <%= "#{event.id}" %> + "/" + $("#bet_amount").val() + "/" + $('input[name="bet[bet_type]"]:checked').attr("data-team"),
				  success: function (data, status) {if (status == 'success') payout = data; else alert("an error occured");}
				});
			}
			calc_payout();

	  		$('#confirm_place_bet div').html('You are about to place a bet on event <strong>' + $('input[name="bet[bet_type]"]:checked').attr('data-team') + ' vs. ' + $('input[name="bet[bet_type]"]:checked').siblings('input[name="bet[bet_type]"]:not(:checked)').attr('data-team') + '</strong><br/><br/>Pick Info...<br>Bet Amount: ' + $("#bet_amount").val() + "<br/>Pick: " + $('input[name="bet[bet_type]"]:checked').attr("data-team") + "<br/>Payout: " + payout);
	  		
		  	var this_local = this;
			confirm_popup = $('#confirm_place_bet').dialog({
				autoOpen: false,
				closeOnEscape: true,
				height: 200,
				width: 400,
				resizable: false,
				modal: true,
				dialogClass: 'overlay',
				buttons: {
					"Confirm" : function () { this_local.submit(); },
					"Cancel" : function () { $(this).dialog("close"); }
				}
			});
			$(".ui-dialog-titlebar").remove();
			confirm_popup.dialog("open");
		}
	  	else
	  		alert("You must select a team to beat the spread, and your wager must be greater than zero.");
	  });
	  
	  $("#over_under_bet_form").submit(function (e) {
	  	e.preventDefault();
	  	if ($(this).children('input[name="bet[bet_type]"]:checked').length > 0 && $(this).children('input[type="number"]').val() > 0) {

			$('#confirm_place_bet div').html('You are about to place a bet on event <strong>' + $('input[name="bet[bet_type]"]:checked').attr('data-team') + ' vs. ' + $('input[name="bet[bet_type]"]:checked').siblings('input[name="bet[bet_type]"]:not(:checked)').attr('data-team') + '</strong><br/><br/>Pick Info...<br>Total Points: ' + $("#bet_amount2").attr('data-total') + '<br/>Bet Amount: ' + $("#bet_amount2").val() + "<br/>Pick: " + $('input[name="bet[bet_type]"]:checked').attr("data-pick") + "<br/>Payout: " + $("#bet_amount2").val());

		  	var this_local = this;
			confirm_popup = $('#confirm_place_bet').dialog({
				autoOpen: false,
				closeOnEscape: true,
				height: 200,
				width: 400,
				resizable: false,
				modal: true,
				dialogClass: 'overlay',
				buttons: {
					"Confirm" : function () { this_local.submit(); },
					"Cancel" : function () { $(this).dialog("close"); }
				}
			});
			$(".ui-dialog-titlebar").remove();
			confirm_popup.dialog("open");
		}
	  	else
	  		alert("You must predict whether the actual total points will be over/under the predicted total, and your wager must be greater than zero.");
	  });
</script>

app/views/bets/_parlay_select_table.html.erb
<div id="parlay_game_list">
	<h2>Select Up to 4 games</h2>
	<div id="parlay_wager">
		<span>Amount: </span><%= number_field_tag :amount, 1, :min => 1, :class => "number_input"%><br />
		<div>Selected games: 
			<ul id="parlay_selected_games">
			</ul>
			<div>Winning payout: <span class="winning_payout">N/A</span></div>
			<%= submit_tag "Place Pick!", :class => 'button place_bet' %>
		</div>
	</div>
	<table id="parlay_game_table">
	<% if games.length > 0 %>	
			<% games.each do |game| %>
			
			<% if sport != game.sport %>
			<tr>
				<td class="table_left"><h2><%= LEAGUE_NAMES_ABBR[game.sport-1] %> Games</h2></td>
				<% sport = game.sport %>
			</tr>
			<tr>
				<td class="table_left">Game Day</td>
				<td>Matchup</td>
				<td>Add to Parlay</td>
			</tr>
			<% end %>
			
			<tr>
				<td class="table_left"> 
					<span>
						<span style="font-weight:bold">
							<%= game.start_time.strftime("%I:%M").upcase %>
						</span>
						<br />
						<%= game.start_time.strftime("%P %Z") %>
						<br />
						<%= game.start_time.strftime("%m-%d ") %>
					</span>
				</td>
				<td>
					<span class="featured_team_name"><%= game.away_team %><span class="spread_text">(
						<% if !game.spread.nil? %>
							<%= -game.spread %>
						<% else %>
							<%= game.moneyline_away %>					 
						<% end %> 
						)</span></span> @ <span class="featured_team_name"><%= game.home_team %><span class="spread_text">(
							<% if !game.spread.nil? %> 
								<%= game.spread %>
							<% else %>
								<%= game.moneyline_home %>
							<% end %>)</span></span>
				</td>
				<td style="display:none" id="<%= 'parlay_event_checkbox_' + game.id.to_s %>" class="table_right">				
					<%= check_box_tag 'event_id[]', game.id %>
					<script id="<%= 'parlay_event_' + game.id.to_s %>" type="text/javascript">
						$(function () {						
							$("#"+"<%= 'parlay_event_' + game.id.to_s %>").siblings('input').change(function (e) {
								if (this.checked) {
									if (num_games == 4) {
										this.checked = false;
										alert("maximum of 4 games in parlay pick!");
									} else {
										num_games += 1;
										$("#parlay_selected_games").append("<li data-id='<%= game.id %>'>Picked <strong>" + $(this).parent().attr('data-bet') + "</strong> on <%= game.away_team %> (" + 
										<% if game.spread.nil? %>
											<%= game.moneyline_away %> 
										<% else %> 
											<%= game.spread %>
										<% end %> + ")" + " @ " + "<%= game.home_team %> (" + 
											<% if game.spread.nil? %>
													<%= game.moneyline_home %> 
											<% else %> 
													<%= game.spread %> 
											<% end %> + ")" + "</li>");					
										if (num_games > 1)	
											$(".winning_payout").text("$" + (parseInt($(".number_input").val()) * parlay_odds[num_games-2]).toFixed(2).toString());
										else
											$(".winning_payout").text("N/A");
									}
								} else {
									num_games -= 1;
									$("#parlay_selected_games").children("li[data-id='<%= game.id %>']").remove();
									if (num_games > 1)	
										$(".winning_payout").text("$" + (parseInt($(".number_input").val()) * parlay_odds[num_games-2]).toFixed(2).toString());
									else
										$(".winning_payout").text("N/A");						
								}
							});
						});
					</script>
				</td>
			</tr>
			<tr>
				<td class="add_border table_left">
				</td>
				<td class="add_border">
					<%= hidden_field_tag "sport[#{game.id}]", game.sport %>
					Pick <%= game.home_team %>: <%= radio_button_tag("bet_type[#{game.id}]", 'home') %>
					Pick <%= game.away_team %>: <%= radio_button_tag("bet_type[#{game.id}]", 'away') %><br/>
					Pick Over (<%= game.total_points %>): <%= radio_button_tag("bet_type[#{game.id}]", 'over') %>
					Pick Under (<%= game.total_points %>): <%= radio_button_tag("bet_type[#{game.id}]", 'under') %>
					<script id="<%= 'parlay_event_bet_' + game.id.to_s %>" type="text/javascript">
						$(function () {
							$("#"+"<%= 'parlay_event_bet_' + game.id.to_s %>").siblings('input').click(function () {
								$("#" + "<%= 'parlay_event_checkbox_' + game.id.to_s %>").show();
								$("#" + "<%= 'parlay_event_checkbox_' + game.id.to_s %>").attr('data-bet', $(this).val());
							});
							
						})
					</script>
				</td>
			</tr>
			<tr><td class="table_left"><br /></td></tr>
			<% end %>		
	<% else %>
			<tr><td>There are no games today for your selected sport</td></tr>	
	<% end %>
	</table>
</div>

app/views/bets/bets_home.html.erb
<h1 class="basic_header">Straight Picks <span class="switch_link"><!--<a href="/make_parlay">Parlay Bet</a>--></span></h1>

<div id="page_right">
	<div id="place_bet_bet_home"></div>
</div>
<div id="page_left">
<%= render :partial => 'events/game_list', :locals => { :games => @games, :sport => @sport } %>
</div>

app/views/bets/index.html.erb
<h1>Listing bets</h1>

<table>
  <tr>
    <th>User</th>
    <th>Event</th>
    <th>Amount</th>
    <th>Bet home</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bets.each do |bet| %>
  <tr>
    <td><%= bet.user_id %></td>
    <td><%= bet.event_id %></td>
    <td><%= bet.amount %></td>
    <td><%= bet.bet_home %></td>
    <td><%= link_to 'Show', bet %></td>
    <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
    <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/make_parlay.html.erb
<%= form_tag '/add_bets_to_parlay' do %>		
	<h1 class="basic_header">Parlay Pick<span class="switch_link"><a href="/bets_home"> Straight Bets</a></span></h1>
	
	<div id="parlay_left">
		<%= render :partial => 'parlay_select_table', :locals => { :games => @games, :sport => @sport } %>
	</div>
		
<% end %>	

app/views/bets/new.html.erb
<%= render :partial => 'bets/new', :locals => {:event => @event, :bet => @bet} %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @bet.user_id %>
</p>

<p>
  <b>Event:</b>
  <%= @bet.event_id %>
</p>

<p>
  <b>Amount:</b>
  <%= @bet.amount %>
</p>

<p>
  <b>Bet home:</b>
  <%= @bet.bet_home %>
</p>


<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>