config/routes.rb
PickingDucks::Application.routes.draw do
  resources :sessions
  resources :events
  resources :bets 
  resources :users 
  resources :events do
    resources :bets
  end
  resources :password_resets
  resources :cashouts
  
  get "/how_to_play" => "application#how_to_play", :as => "how_to_play"
  get "/privacy" => "application#privacy", :as => "privacy"
  get "/terms_of_service" => "application#terms_of_service", :as => "terms_of_service"
  get "/about_us" => "application#about_us", :as => "about_us"
  
  get 'public_profile/:id' => "users#public_profile", :as => "public_profile"
  get 'pay_for_bet/:user_id/:bet_id' => "users#pay_for_bet", :as => "pay_for_bet"
  get 'pay_money_for_bet/:user_id/:bet_id' => "users#pay_money_for_bet", :as => "pay_money_for_bet"
  
  get "/sport/:sport_id" => "sports#sport_home", :as => "sport_home"
  
  get "/bets_home" => "bets#bets_home", :as => "bets_home"
  get "/make_parlay" => "bets#make_parlay", :as => "make_parlay"
  get "/request_cashout" => "users#request_cashout", :as => "request_cashout"
  get "/get_bets_for_date" => "users#get_bets_for_date", :as => "get_bets_for_date"
  get '/calc_payout/:event_id/:amount/:pick' => "bets#calc_payout", :as => "calc_payout"
  get '/reset_ducks' => 'users#reset_ducks', :as => "reset_ducks"
  post "/add_bets_to_parlay" => "bets#add_bets_to_parlay", :as => "add_bets_to_parlay"
  post '/make_bet_private/:id' => "bets#make_bet_private", :as => "make_bet_private"
  post '/buy_ducks' => "users#buy_duck", :as => "buy_ducks"
  post '/buy_bet_info' => "users#buy_bet_info", :as => "buy_bet_info"
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "user#new", :as => "sign_up"
  get "get_featured" => "home#get_featured", :as => "get_featured"
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bets, :order => 'created_at DESC'
  has_many :parlays, :order => 'created_at DESC'
  has_many :purchases, :order => 'created_at DESC'
  has_many :cashouts  
  
  attr_accessor :password
  attr_accessible :profile_pic, :bio, :dob, :email, :first_name, :active, :last_name, :password, :password_confirmation, :secret_answer, :secret_question, :username, :accept_terms, :wins, :losses, :ties, :bankroll, :money, :nfl_wins, :nfl_losses, :nfl_ties, :nba_wins, :nba_losses, :nba_ties, :mlb_wins, :mlb_losses, :mlb_ties, :nhl_wins, :nhl_losses, :nhl_ties, :registered, :address1, :address2, :city, :state, :zip
  
  has_attached_file :profile_pic, :styles => { :medium => "200x200", :thumb => "100x100" }, :default_url => "/images/missing.jpg"
   
  before_create :encrypt_password

  before_create { generate_token(:auth_token) }
  
  validates_presence_of :password, :on => :create
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :username
  validates_confirmation_of :password
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_numericality_of :bankroll, :greater_than => 0
  
  def assign_win_percentage
    self.win_percentage = wins.to_f / (wins + losses + ties)
  end
  def assign_nfl_win_percentage
    self.nfl_win_percentage = nfl_wins.to_f / (nfl_wins + nfl_losses + nfl_ties)
  end
  def assign_nba_win_percentage
    self.nba_win_percentage = nba_wins.to_f / (nba_wins + nba_losses + nba_ties)
  end
  def assign_mlb_win_percentage
    self.mlb_win_percentage = mlb_wins.to_f / (mlb_wins + mlb_losses + mlb_ties)
  end
  def assign_nhl_win_percentage
    self.nhl_win_percentage = nhl_wins.to_f / (nhl_wins + nhl_losses + nhl_ties)
  end
  def self.authenticate(email, password)
    user = find_by_email(email.downcase)
    if user && user.pwd_hash == BCrypt::Engine.hash_secret(password, user.pwd_salt)
      user
    else
      nil
    end
  end
  
  def past_week_earnings_straight
    past_week_bets = bets.where('closed_at > ? and parlay = false and pending = false ', 7.days.ago)
    total = 0
    past_week_bets.each do |bet|
      if bet.winning
        total += bet.amount
      else
        total -= bet.amount
      end
    end
    total
  end
    
  def past_week_earnings_nfl
    past_week_bets = bets.where('closed_at > ? and parlay = false and pending = false and sport = 1', 7.days.ago)
    total = 0
    past_week_bets.each do |bet|
      if bet.winning
        total += bet.amount
      else
        total -= bet.amount
      end
    end
    total
  end
  
  def past_week_earnings_nba
    past_week_bets = bets.where('closed_at > ? and parlay = false and pending = false and sport = 2', 7.days.ago)
    total = 0
    past_week_bets.each do |bet|
      if bet.winning
        total += bet.amount
      else
        total -= bet.amount
      end
    end
    total
  end
  
  def past_week_earnings_mlb
    past_week_bets = bets.where('closed_at > ? and parlay = false and pending = false and sport = 3', 7.days.ago)
    total = 0
    past_week_bets.each do |bet|
      if bet.winning
        total += bet.amount
      else
        total -= bet.amount
      end
    end
    total
  end
  
  def past_week_earnings_nhl
    past_week_bets = bets.where('closed_at > ? and parlay = false and pending = false and sport = 4', 7.days.ago)
    total = 0
    past_week_bets.each do |bet|
      if bet.winning
        total += bet.amount
      else
        total -= bet.amount
      end
    end
    total
  end
  
  def encrypt_password
    self.pwd_salt = BCrypt::Engine.generate_salt
    self.pwd_hash = BCrypt::Engine.hash_secret(password, pwd_salt)
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def self.search(search)
    if search
      where('username LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
  
end

app/controllers/users_controller.rb
require 'will_paginate'

class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  def request_cashout
    @cashout = Cashout.new
  end
  
  def buy_ducks
    begin
      charge = Stripe::Charge.create(
        :amount => 5 * params[:amount].to_i,
        :currency => "usd",
        :card => params[:stripe_card_token],
        :description => current_user.email
      )
      logger.info "BUY DUCK CHARGE WAS MADE. RECEIPT TOKEN: " + charge.id
      current_user.bankroll += params[:amount].to_i
      purchase = current_user.purchases.build
      purchase.stripe_payment_token = charge.id
      purchase.amount = params[:amount].to_i
      current_user.save
      flash[:notice] = "Your ducks have been purchased and added to your bankroll!"
      redirect_to user_path(current_user)
    rescue Stripe::CardError => e
      flash[:error] = "There was a problem processing your credit card information."
      redirect_to user_path(current_user)
    end
  end

  def reset_ducks
    current_user.bankroll = 1000
    current_user.available_bankroll = 1000
    current_user.bets.where(:pending => true).destroy_all
    current_user.save!
    flash[:notice] = "Your ducks have been reset to 1000, and any open picks were destroyed."
    redirect_to user_path(current_user)
  end
  
  def buy_bet_info
    begin
      charge = Stripe::Charge.create(
        :amount => params[:amount].to_i,
        :currency => "usd",
        :card => params[:stripe_card_token],
        :description => current_user.email
      )
      logger.info "BUY BET INFO CHARGE WAS MADE. RECEIPT TOKEN: " + charge.id
      current_user.bankroll += params[:amount].to_i
      purchase = current_user.purchases.build
      purchase.stripe_payment_token = charge.id
      purchase.amount = params[:amount].to_i
      purchase.bet_id = params[:bet_id]
      current_user.save
      flash[:notice] = "Your credit card has been charged, and you can now see the bet information you purchased."
      redirect_to user_path(current_user)
    rescue Stripe::CardError => e
      flash[:error] = "There was a problem processing your credit card information."
      redirect_to user_path(current_user)
    end
  end
  
  def show
    @pending_bets = current_user.bets.where(:pending => true, :parlay => false)
    @parlays = current_user.parlays.where(:pending => true)
       
    @past_straights = current_user.bets.where(:pending => false, :parlay => false).order('closed_at').reverse
    @past_ten_days = current_user.bets.where(:pending => false, :parlay => false).where('closed_at >= ?', 10.days.ago).order('closed_at DESC')
    @past_thirty_days = current_user.bets.where(:pending => false, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at DESC')
    
    @past_parlays = current_user.parlays.where(:pending => false).order('closed_at').reverse
        
    @nfl_past_bets = current_user.bets.where(:pending => false, :sport => 1, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at DESC').reverse
    @nfl_change_dates = @nfl_past_bets.map(&:closed_at).map {|date| date.strftime('%b')}
    @nba_past_bets = current_user.bets.where(:pending => false, :sport => 2, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at DESC').reverse   
    @nba_change_dates = @nba_past_bets.map(&:closed_at).map {|date| date.strftime('%b')}
    @mlb_past_bets = current_user.bets.where(:pending => false, :sport => 3, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at DESC').reverse    
    @mlb_change_dates = @mlb_past_bets.map(&:closed_at).map {|date| date.strftime('%b')}
    @nhl_past_bets = current_user.bets.where(:pending => false, :sport => 4, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at DESC').reverse
    @nhl_change_dates = @nhl_past_bets.map(&:closed_at).map {|date| date.strftime('%b')}
        
    @straight_change_dates = @past_straights.map(&:closed_at).map {|date| date.strftime('%b')}       
    @parlay_change_dates = @past_parlays.map(&:closed_at).map {|date| date.strftime('%b')}
    @bankroll_history.to_json.html_safe
    @change_hash = @change_hash.to_json.html_safe
    
    @bet_sales = []
    current_user.bets.order('created_at ASC').each do |bet|
      @bet_sales << bet.purchases
      @bet_sales.flatten!
      if @bet_sales.length >= 10
        break;
      end
    end    
    
    @rank = User.where('bankroll > ?', current_user.bankroll).count + 1
    
    @past_week_earnings_straight = current_user.past_week_earnings_straight
    @past_week_earnings_nfl = current_user.past_week_earnings_nfl
    @past_week_earnings_nba = current_user.past_week_earnings_nba
    @past_week_earnings_mlb = current_user.past_week_earnings_mlb
    @past_week_earnings_nhl = current_user.past_week_earnings_nhl
    
  end

  def get_bets_for_date
    if params[:user]
      @user = User.find(params[:user].to_i)
      if params[:ten_days]
        @date_bets = @user.bets.where(:pending => false, :parlay => false).where('closed_at >= ?', 10.days.ago).order('closed_at DESC')
      else 
        @date_bets = @user.bets.where("closed_at between ? and ?", params[:date].to_i.days.ago.beginning_of_day, params[:date].to_i.days.ago.end_of_day) 
      end 
    else
      if params[:ten_days]
        @date_bets = current_user.bets.where(:pending => false, :parlay => false).where('closed_at >= ?', 10.days.ago).order('closed_at DESC')
      else
        @date_bets = current_user.bets.where("closed_at between ? and ?", params[:date].to_i.days.ago.beginning_of_day, params[:date].to_i.days.ago.end_of_day) 
      end
    end
    render 'users/get_bets_for_date.js.erb'
  end
  
  def public_profile
    @user = User.find(params[:id]) 
    @past_ten_days = @user.bets.where(:pending => false, :parlay => false).where('closed_at >= ?', 10.days.ago).order('closed_at DESC')   
    @past_thirty_days = @user.bets.where(:pending => false, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at DESC')
    @pending_bets = @user.bets.where(:pending => true, :parlay => false)
    
    @past_straights = @user.bets.where(:pending => false, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at ASC')
    @past_parlays = @user.parlays.where(:pending => false).order('closed_at ASC')        
    
    @nfl_past_bets = @user.bets.where(:pending => false, :sport => 1, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at ASC')
    @nfl_change_dates = @nfl_past_bets.map(&:closed_at).map {|date| date.strftime('%b')}
    @nba_past_bets = @user.bets.where(:pending => false, :sport => 2, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at ASC')   
    @nba_change_dates = @nba_past_bets.map(&:closed_at).map {|date| date.strftime('%b')}
    @mlb_past_bets = @user.bets.where(:pending => false, :sport => 3, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at ASC')    
    @mlb_change_dates = @mlb_past_bets.map(&:closed_at).map {|date| date.strftime('%b')}
    @nhl_past_bets = @user.bets.where(:pending => false, :sport => 4, :parlay => false).where('closed_at >= ?', 30.days.ago).order('closed_at ASC')
    @nhl_change_dates = @nhl_past_bets.map(&:closed_at).map {|date| date.strftime('%b')}    
    
    @straight_change_dates = @past_straights.map(&:closed_at).map {|date| date.strftime('%b')}       
    @parlay_change_dates = @past_parlays.map(&:closed_at).map {|date| date.strftime('%b')}
    @bankroll_history.to_json.html_safe
    @change_hash = @change_hash.to_json.html_safe
    
    @past_week_earnings_straight = @user.past_week_earnings_straight
    @past_week_earnings_nfl = @user.past_week_earnings_nfl
    @past_week_earnings_nba = @user.past_week_earnings_nba
    @past_week_earnings_mlb = @user.past_week_earnings_mlb
    @past_week_earnings_nhl = @user.past_week_earnings_nhl
    
    if !current_user.nil?
      @rank = User.where('bankroll > ?', current_user.bankroll).count + 1 
    end
  end
    
=begin  
  def pay_for_bet
    bet = Bet.find(params[:bet_id])
    user = User.find(params[:user_id])
    
    if bet.duck_price <= current_user.bankroll
      current_user.bankroll -= bet.duck_price
      purchase = current_user.purchases.build
      purchase.bet = bet
      user.bankroll += bet.duck_price
      
      if current_user.save && user.save
          flash[:notice] = "Bet purchased!"
          return redirect_to public_profile_path(user.id)
      else
          flash[:error] = "An error occured.<br />"
          flash[:error] << user.errors.full_messages.collect { |msg| msg + "<br/>" }.join
          flash[:error] << current_user.errors.full_messages.collect { |msg| msg + "<br/>" }.join
          return redirect_to public_profile_path(user)
      end
    else
      flash[:alert] = "You do not have enough ducks to purchase this information"
      return redirect_to public_profile user
    end  
    return redirect_to public_profile_path(user.id)  
  end
=end  
  def pay_money_for_bet
    @bet = Bet.find(params[:bet_id])
    @user = User.find(params[:user_id])    
  end
  
  def new
  end
  
  def register
    
  end
  
  def update
    current_user.update_attributes(params[:user])
    flash[:notice] = "Account details updated!"
    redirect_to :action => 'show'
  end
  
  def create
    @user = User.new(params[:user])
    @user.email = params[:user][:email].downcase
    @user.wins = 0
    @user.losses = 0
    @user.ties = 0
    @user.bankroll = 1000.0
    
    if @user.save
      #UserMailer.registration_confirmation(@user).deliver
      cookies[:auth_token] = @user.auth_token
      flash.notice = "Signed up!"
      redirect_to root_url
    else
      logger.info @user.errors.full_messages
      flash[:error] = "An error occured with sign up.<br />"
      flash[:error] << @user.errors.full_messages.collect { |msg| msg + "<br/>" }.join
      redirect_to root_url
    end
  end
  
  def index

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_past_bets_table.html.erb
<% if past_bets.length > 0 %>
	<table class="past_wagers_table">
		<thead>
			<tr>
				<th>Gameday</th>
				<th>Event</th>
				<th>Final Score</th>
				<th>Pick</th>
				<th>Amount</th>		 			
				<th>Outcome</th>
				<th>Ducks+-</th>
				<th>Resulting Bankroll</th>
			</tr>
		</thead>	
	<% past_bets.each do |bet| %>
	<tbody>
		<tr class="past_bet_info">
		<td>
			<%= bet.event.start_time.strftime("%m-%d") %>
		</td>
		<% if !bet.event.spread.nil? %>
			<td><%= "#{bet.event.away_team}(#{-bet.event.spread})@#{bet.event.home_team}(#{bet.event.spread})"%></td>
		<% else %>
			<td><%= "#{bet.event.away_team}(#{bet.event.moneyline_away})@#{bet.event.home_team}(#{bet.event.moneyline_home})"%></td>
		<% end %>	 
		<td><%= "#{bet.event.away_total.round(0)}-#{bet.event.home_total.round(0)}" %></td>			
		<td><%= bet.event.bet_type(bet.bet_type) %></td>
		<td><%= bet.amount %>d</td> 				
		<% if bet.winning? %>
			<td style="color:green">WIN</td>
		<% else %>
			<td style="color:red">LOSS</td>
		<% end %>
		<% if !bet.winning? %>
			<td>(-)<%= bet.amount %></td>
		<% else %>
			<% if !bet.event.spread.nil? %>	 				
				<td>(+)<%= bet.amount %></td>
			<% else %>
			  <% if bet.bet_type == "home" %>
	            <% if bet.event.moneyline_home > 0 %>
	              <td>(+)<%= bet.amount * bet.event.moneyline_home / 100 %></td>
	            <% else %>
	              <td>(+)<%= bet.amount * 100 / bet.event.moneyline_home.abs %></td>
	            <% end %>
	      <% elsif bet.bet_type == "away" %>
	        <% if bet.event.moneyline_away > 0 %>
	          <td>(+)<%= bet.amount * bet.event.moneyline_away / 100 %></td>
	        <% else %>
	          <td>(+)<%= bet.amount * 100 / bet.event.moneyline_away.abs %></td>
	        <% end %>
	      <% else %>
				<td>(+)<%= bet.amount %></td>
			  <% end %>
			<% end %>
		<% end %>
		<td><%= bet.resulting_bankroll %>d</td>
		</tr>
	</tbody>
	<% end %>
	</table>
	 <button class="past_ten_days_btn"><a onclick="$.getScript('/get_bets_for_date?ten_days=1<%= "&user=#{user.id}" if !user.nil? %>')">See past ten days</a></button>
<% else %>
<span>
	No pick history for this date.
</span>
<button class="past_ten_days_btn"><a onclick="$.getScript('/get_bets_for_date?ten_days=1<%= "&user=#{user.id}" if !user.nil? %>')">See past ten days</a></button>
<% end %>

app/views/users/_top_ten_table.html.erb
<h2>Top Ten</h2>
<span class="featured_date"></span>
<table id="top_ten_users_table">
	<tr>
		<th>Rank</th>
		<th>Username</th>
		<th>WLT</th>
		<th>Win%</th>
		<th>Units</th>
	</tr>
	<% 10.times do |i| %>
		<% user = top_ten[i] %>
		<% if user %>
			<tr>
				<td><%= i + 1 %></td>
				<td><%= user.username %></td>
				<td><%= "#{user.wins}-#{user.losses}-#{user.ties}" %></td>
				<td><%= ((user.wins.to_f / (user.wins + user.losses + user.ties))*100).round(2) %></td>
				<td><%= user.bankroll.round(2) %></td>
			</tr>
		<% else %>
			<tr>
				<td><%= i + 1 %></td>
				<td colspan="4"></td>
			</tr>
		<% end %>	
	<% end %>
</table>

app/views/users/_users.html.erb
<%= form_tag users_path, :method => 'get', :id => "users_search" do %>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
<table id="users_table">
	<tr>
		<th class="table_left">Rank</td></th>
		<th><%= sortable 'username', 'Username' %></th>
		<th><%= sortable 'wins', 'W-L-T' %></th>
		<th><%= sortable 'nfl_wins', 'NLF Record' %></th>
		<th><%= sortable 'nba_wins', 'NBA Record' %></th>
		<th><%= sortable 'mlb_wins', 'MLB Record' %></th>
		<th><%= sortable 'nhl_wins', 'NHL Record' %></th>
		<th><%= sortable 'win_percentage', 'Win%' %></th>		
		<th><%= sortable 'nfl_win_percentage', "NFL Win%" %></th>
		<th><%= sortable 'nba_win_percentage', "NBA Win%" %></th>
		<th><%= sortable 'mlb_win_percentage', "MLB Win%" %></th>
		<th><%= sortable 'nhl_win_percentage', "NHL Win%" %></th>
		<th><%= sortable 'bankroll', 'Ducks' %></th>
	</tr>
	<% @users.each_with_index do |user, i| %>
			<tr>
				<% if params[:page] %>
				<td class="table_left"><%= i + 1 + (params[:page].to_i - 1)* params[:per_page].to_i %></td>
				<% else %>
				<td class="table_left"><%= i + 1 %></td>
				<% end %>
				<td><a href="<%= public_profile_path user.id %>"><%= user.username %></a></td>
				<td><%= "#{user.wins}-#{user.losses}-#{user.ties}" %></td>
				<td><%= "#{user.nfl_wins}-#{user.nfl_losses}-#{user.nfl_ties}" %></td>
				<td><%= "#{user.nba_wins}-#{user.nba_losses}-#{user.nba_ties}" %></td>
				<td><%= "#{user.mlb_wins}-#{user.mlb_losses}-#{user.mlb_ties}" %></td>
				<td><%= "#{user.nhl_wins}-#{user.nhl_losses}-#{user.nhl_ties}" %></td>
				<td><%= (100* user.win_percentage).round(2) %>%</td>
				<td><%= (100* user.nfl_win_percentage).round(2) %>%</td>
				<td><%= (100* user.nba_win_percentage).round(2) %>%</td>
				<td><%= (100* user.mlb_win_percentage).round(2) %>%</td>
				<td><%= (100* user.nhl_win_percentage).round(2) %>%</td>
				<td><%= user.bankroll.round(2) %></td>
			</tr>		
	<% end %>
	<tr>
		<td colspan="13">
			<%= will_paginate @users, :class => "duck_pagination" %>
		</td>
	</tr>
</table>

app/views/users/get_bets_for_date.js.erb
$("#past_bets_table").html($("<%= escape_javascript(render :partial => 'users/past_bets_table', :locals => {:past_bets => @date_bets, :user => @user }) %>"));

app/views/users/index.html.erb
<div id="users">
<%= render :partial => 'users/users' %>
</div>

app/views/users/index.js.erb
$("#users").html("<%= escape_javascript(render :partial => 'users/users') %>")

app/views/users/new.html.erb
<div id="sign_up">
	<%= image_tag (asset_path "PD_logo.png"), :class => "overlay_logo_signup" %> 
	<span class="close_button">x</span>
	<div class="sign_up_form_wrapper">				
		<h2>Create an Account</h2>
		<h6>All Fields Required</h6>
		
		<%= form_for user, :html => {:id => 'sign_up_form'} do |f| %>
		 <p>
		 	<%= f.label :first_name, :class => "reg_label" %>: 
		 	<%= f.text_field :first_name %>
		 </p>
		 <p>
		 	<%= f.label :last_name, :class => "reg_label" %>: 
		 	<%= f.text_field :last_name %>
		 </p>
		 <p>
		 	<%= f.label :email, :class => "reg_label" %>: 
		 	<%= f.text_field :email %>
		 </p>
		 <p>
		 	<%= f.label :username, :class => "reg_label" %>: 
		 	<%= f.text_field :username %>
		 </p>
		 <p>
		 	<%= f.label :password, :class => "reg_label" %>: 
		 	<%= f.password_field :password %>
		 </p>
		 <p>
		 	<%= f.label :password_confirmation, :class => "reg_label" %>: 
		 	<%= f.password_field :password_confirmation %>
		 </p>
		 <p>
		 	<%= f.check_box :accept_terms %> <span style="display:inline; font-size:12px;">I agree to the <a class="terms_link" target="_blank" href="/terms_of_service">terms of service</a> and the <a class="terms_link" target="_blank" href="/privacy">privacy policy</a>
		 </p>
		 <p><%= f.submit 'Create Account', :class => 'button create_accnt submit_btn' %></p>
		<% end %>
		<p id="sign_up_error"></p>
	</div>
</div>

app/views/users/pay_money_for_bet.html.erb
<h1>Pay Money For Pick Info</h1>

<%= form_tag buy_bet_info_path, :id => "buy_bet_info_form" do %>	
	<%= hidden_field_tag :stripe_card_token %>
	<%= hidden_field_tag :bet_id, @bet.id %>
	<%= hidden_field_tag :amount, @bet.money_price * 100, :id => "bet_money_price"%>
	<p>
		<div>
			<% if !@bet.event.spread.nil? %>
			To see information for this pick for event <%= "#{bet.event.away_team}(#{-bet.event.spread}) @ #{bet.event.home_team}(#{bet.event.spread}) on #{@bet.event.start_time.strftime('%m-%d ')} " %> by <%= link_to @user.username, user_path(@user.id) %>, you must pay <%= @bet.money_price %> dollars.
			<% else %>
			To see information for this pick for event <%= "#{@bet.event.away_team}(#{@bet.event.moneyline_away}) @ #{@bet.event.home_team}(#{@bet.event.moneyline_home}) on #{@bet.event.start_time.strftime('%m-%d ')} " %> by <%= link_to @user.username, user_path(@user.id) %>, you must pay <%= @bet.money_price %> dollars.
			<% end %>
		</div>
	</p>
	<p>
		<%= label_tag :card_number, "Credit Card Number" %>
		<%= text_field_tag :card_number, nil, name: nil %>
	</p>
	<p>
		<%= label_tag :card_code, "Security Code (CVV) "%>
		<%= text_field_tag :card_code, nil, name: nil %>
	</p>
	<p>
		<%= label_tag :card_month, "Card Expiration" %>
		<%= select_month nil, {add_month_numers: true}, {name:nil, id: "card_month"} %>
		<%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year + 15}, {name: nil, id: "card_year"} %>
	</p>
	<p><%= submit_tag 'Buy Pick Info!', :class => 'button submit_btn', :id => "buy_ducks_btn" %></p>
	<span id="stripe_error" class="flash_error">
		<noscript>
			JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
		</noscript>
	</span>
<% end %>
<div class="confirm_buy_bet_info">
	<h4>Purchase Pick Info?</h4>
	<span></span>
</div>