config/routes.rb
PickingDucks::Application.routes.draw do
  resources :sessions
  resources :events
  resources :bets 
  resources :users 
  resources :events do
    resources :bets
  end
  resources :password_resets
  resources :cashouts
  
  get "/how_to_play" => "application#how_to_play", :as => "how_to_play"
  get "/privacy" => "application#privacy", :as => "privacy"
  get "/terms_of_service" => "application#terms_of_service", :as => "terms_of_service"
  get "/about_us" => "application#about_us", :as => "about_us"
  
  get 'public_profile/:id' => "users#public_profile", :as => "public_profile"
  get 'pay_for_bet/:user_id/:bet_id' => "users#pay_for_bet", :as => "pay_for_bet"
  get 'pay_money_for_bet/:user_id/:bet_id' => "users#pay_money_for_bet", :as => "pay_money_for_bet"
  
  get "/sport/:sport_id" => "sports#sport_home", :as => "sport_home"
  
  get "/bets_home" => "bets#bets_home", :as => "bets_home"
  get "/make_parlay" => "bets#make_parlay", :as => "make_parlay"
  get "/request_cashout" => "users#request_cashout", :as => "request_cashout"
  get "/get_bets_for_date" => "users#get_bets_for_date", :as => "get_bets_for_date"
  get '/calc_payout/:event_id/:amount/:pick' => "bets#calc_payout", :as => "calc_payout"
  get '/reset_ducks' => 'users#reset_ducks', :as => "reset_ducks"
  post "/add_bets_to_parlay" => "bets#add_bets_to_parlay", :as => "add_bets_to_parlay"
  post '/make_bet_private/:id' => "bets#make_bet_private", :as => "make_bet_private"
  post '/buy_ducks' => "users#buy_duck", :as => "buy_ducks"
  post '/buy_bet_info' => "users#buy_bet_info", :as => "buy_bet_info"
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "user#new", :as => "sign_up"
  get "get_featured" => "home#get_featured", :as => "get_featured"
  root :to => "home#index"

end

app/models/event.rb
require 'nokogiri'
require 'open-uri'
require 'date'

class Event < ActiveRecord::Base
  has_many :bets
  
  attr_accessible :sport, :spread, :moneyline_home, :moneyline_away, :total_points, :start_time, :live, :finished, :home_team, :home_location, :away_team, :away_location, :extern_id
  
  scope :popular_events_nfl, joins(:bets).where(:sport => 1).group('events.id').having('count(bets.id) >= 10')
  scope :popular_events_nba, joins(:bets).where(:sport => 2).group('events.id').having('count(bets.id) >= 10')
  scope :popular_events_mlb, joins(:bets).where(:sport => 3).group('events.id').having('count(bets.id) >= 10')
  scope :popular_events_nhl, joins(:bets).where(:sport => 4).group('events.id').having('count(bets.id) >= 10')
  
  def self.find_consensus_picks
    consensus_picks = []
    nfl_consensus = nil
    popular_events_nfl.each do |event|
      if nfl_consensus == nil
        nfl_consensus = event
      else
        if event.consensus[1] > nfl_consensus.consensus[1]
          nfl_consensus = event
        end
      end
    end 
    nba_consensus = nil
    popular_events_nba.each do |event|
      if nba_consensus == nil
        nba_consensus = event
      else
        if event.consensus[1] > nba_consensus.consensus[1]
          nba_consensus = event
        end
      end
    end
    mlb_consensus = nil
    popular_events_mlb.each do |event|
      if mlb_consensus == nil
        mlb_consensus = event
      else
        if event.consensus[1] > mlb_consensus.consensus[1]
          mlb_consensus = event
        end
      end
    end
    nhl_consensus = nil
    popular_events_nhl.each do |event|
      if nhl_consensus == nil
        nhl_consensus = event
      else
        if event.consensus[1] > nhl_consensus.consensus[1]
          nhl_consensus = event
        end
      end
    end
    [nfl_consensus, nba_consensus, mlb_consensus, nhl_consensus].compact
  end
  
  def bet_type(bet_type)
    case bet_type
    when 'home'
      home_team
    when 'away'
      away_team
    when 'over'
      'Over'
    when 'under'
      'Under'
    end
  end
  
  def consensus
    home_count = bets.where(:bet_type => 'home').count
    away_count = bets.where(:bet_type => 'away').count
    over_count = bets.where(:bet_type => 'over').count
    under_count = bets.where(:bet_type => 'under').count
    return [[home_team, home_count], [away_team, away_count], ['Over', over_count], ['Under', under_count]].at([home_count, away_count, over_count, under_count].index([home_count, away_count, over_count, under_count].max))
  end
  
  def self.parse_events
    #
    # U: prosperitech
    # P: l1v3l0ng
    #
    
    
    nfl_odds_url = "http://sportscaster.xmlteam.com/gateway/php_ci/searchDocuments.php?sport-keys=l.nfl.com&league-keys=l.nfl.com&fixture-keys=odds&date-window=16800revision-control=all&publisher-keys=sportsnetwork.com&max-result-count=5&content-returned=all-content&content-format=sportsml&rendering-engine=xslt&gateway-theme=default&query-debug=false"
    
    nba_odds_url = "http://sportscaster.xmlteam.com/gateway/php_ci/searchDocuments.php?sport-keys=l.nba.com&league-keys=l.nba.com&fixture-keys=odds&date-window=16800revision-control=all&publisher-keys=sportsnetwork.com&max-result-count=5&content-returned=all-content&content-format=sportsml&rendering-engine=xslt&gateway-theme=default&query-debug=false"
    
    mlb_odds_url = "http://sportscaster.xmlteam.com/gateway/php_ci/searchDocuments.php?sport-keys=l.mlb.com&league-keys=l.mlb.com&fixture-keys=odds&date-window=16800&revision-control=all&publisher-keys=sportsnetwork.com&max-result-count=5&content-returned=all-content&content-format=sportsml&rendering-engine=xslt&gateway-theme=default&query-debug=false"
    
    nhl_odds_url = "http://sportscaster.xmlteam.com/gateway/php_ci/searchDocuments.php?sport-keys=l.nhl.com&league-keys=l.nhl.com&fixture-keys=odds&date-window=16800revision-control=all&publisher-keys=sportsnetwork.com&max-result-count=5&content-returned=all-content&content-format=sportsml&rendering-engine=xslt&gateway-theme=default&query-debug=false"
    
    xml_doc = Nokogiri::XML(open(nfl_odds_url, :http_basic_authentication => ["prosperitech", "l1v3l0ng"]))
    xml_doc.xpath('//sports-event').each do |event|      
      event_key = event.xpath('./event-metadata/@event-key').to_s
      one_event = Event.find_by_extern_id(event_key)
      if one_event.nil? || (one_event.spread.nil? && one_event.moneyline_home.nil?)
        one_event.destroy if !one_event.nil?
        new_event = Event.new
        new_event.extern_id = event_key
        new_event.start_time = DateTime.parse(event.xpath('./event-metadata/@start-date-time').to_s)
        new_event.sport = 1
        event.xpath('./team').each do |team|
          if team.xpath('./team-metadata/@alignment').to_s == 'home'
            new_event.home_location = team.xpath('./team-metadata/name/@first').to_s
            new_event.home_team = team.xpath('./team-metadata/name/@last').to_s
          else
            new_event.away_location = team.xpath('./team-metadata/name/@first').to_s
            new_event.away_team = team.xpath('./team-metadata/name/@last').to_s
          end
        end        
        new_event.spread = event.xpath('./team/team-metadata[@alignment="home"]/../wagering-stats/wagering-straight-spread[1]/@value').to_s     
        new_event.total_points = event.xpath('./team/team-metadata[@alignment="home"]/../wagering-stats/wagering-total-score[1]/@total').to_s       
        
        new_event.save!
     end     
    end  
    
    xml_doc = Nokogiri::XML(open(nba_odds_url, :http_basic_authentication => ["prosperitech", "l1v3l0ng"]))
    xml_doc.xpath('//sports-event').each do |event|      
      event_key = event.xpath('./event-metadata/@event-key').to_s
      one_event = Event.find_by_extern_id(event_key)
      if one_event.nil? || (one_event.spread.nil? && one_event.moneyline_home.nil?)
        one_event.destroy if !one_event.nil?
        new_event = Event.new
        new_event.extern_id = event_key
        new_event.start_time = DateTime.parse(event.xpath('./event-metadata/@start-date-time').to_s)
        new_event.sport = 2
        event.xpath('./team').each do |team|
          if team.xpath('./team-metadata/@alignment').to_s == 'home'
            new_event.home_location = team.xpath('./team-metadata/name/@first').to_s
            new_event.home_team = team.xpath('./team-metadata/name/@last').to_s
          else
            new_event.away_location = team.xpath('./team-metadata/name/@first').to_s
            new_event.away_team = team.xpath('./team-metadata/name/@last').to_s
          end
        end        
        new_event.spread = event.xpath('./team/team-metadata[@alignment="home"]/../wagering-stats/wagering-straight-spread[1]/@value').to_s 
        new_event.total_points = event.xpath('./team/team-metadata[@alignment="home"]/../wagering-stats/wagering-total-score[1]/@total').to_s       
        
        new_event.save!
      end     
    end      
        
    xml_doc = Nokogiri::XML(open(mlb_odds_url, :http_basic_authentication => ["prosperitech", "l1v3l0ng"]))
    xml_doc.xpath('//sports-event').each do |event|      
      event_key = event.xpath('./event-metadata/@event-key').to_s
      one_event = Event.find_by_extern_id(event_key)
      if one_event.nil? || (one_event.spread.nil? && one_event.moneyline_home.nil?)
        one_event.destroy if !one_event.nil?
        new_event = Event.new
        new_event.extern_id = event_key
        new_event.start_time = DateTime.parse(event.xpath('./event-metadata/@start-date-time').to_s)
        new_event.sport = 3
        event.xpath('./team').each do |team|
          if team.xpath('./team-metadata/@alignment').to_s == 'home'
            new_event.home_location = team.xpath('./team-metadata/name/@first').to_s
            new_event.home_team = team.xpath('./team-metadata/name/@last').to_s
          else
            new_event.away_location = team.xpath('./team-metadata/name/@first').to_s
            new_event.away_team = team.xpath('./team-metadata/name/@last').to_s
          end
        end        
        new_event.moneyline_home = event.xpath('./team/team-metadata[@alignment="home"]/../wagering-stats/wagering-moneyline[1]/@line').to_s   
        new_event.moneyline_away = event.xpath('./team/team-metadata[@alignment="away"]/../wagering-stats/wagering-moneyline[1]/@line').to_s     
        new_event.total_points = event.xpath('./team/team-metadata[@alignment="home"]/../wagering-stats/wagering-total-score[1]/@total').to_s       
        
        new_event.save!
      end     
    end  
    
    xml_doc = Nokogiri::XML(open(nhl_odds_url, :http_basic_authentication => ["prosperitech", "l1v3l0ng"]))
    xml_doc.xpath('//sports-event').each do |event|      
      event_key = event.xpath('./event-metadata/@event-key').to_s
      one_event = Event.find_by_extern_id(event_key)
      if one_event.nil? || (one_event.spread.nil? && one_event.moneyline_home.nil?)
        one_event.destroy if !one_event.nil?
        new_event = Event.new
        new_event.extern_id = event_key
        new_event.start_time = DateTime.parse(event.xpath('./event-metadata/@start-date-time').to_s)
        new_event.sport = 4
        event.xpath('./team').each do |team|
          if team.xpath('./team-metadata/@alignment').to_s == 'home'
            new_event.home_location = team.xpath('./team-metadata/name/@first').to_s
            new_event.home_team = team.xpath('./team-metadata/name/@last').to_s
          else
            new_event.away_location = team.xpath('./team-metadata/name/@first').to_s
            new_event.away_team = team.xpath('./team-metadata/name/@last').to_s
          end
        end        
        new_event.moneyline_home = event.xpath('./team/team-metadata[@alignment="home"]/../wagering-stats/wagering-moneyline[1]/@line').to_s   

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])        
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_featured_games.html.erb
<table id="featured_games_table">
<% if featured.length > 0 %>
	<tr>
		<th>Start Time</th>
		<th>Matchup</th>
		<% if featured[0].sport == 3 %>
		<th>Moneyline</th>
		<% else %>
		<th>Handicap</th>
		<% end %>
		<th>Total Points</th>
		<th></th>
	</tr>
	<% featured.each do |game| %>
	<tr>
		<td>
			<span style="font-weight:bold"><%= game.start_time.strftime("%I:%M").upcase %></span><br />
			<%= game.start_time.strftime("%P %Z") %>
			<br />
			<%= game.start_time.strftime("%m-%d ") %>
		</td>
		<td>
			<span class="featured_team_name"><%= game.away_team %>@</span><br/> <span class="featured_team_name"><%= game.home_team %></span>
		</td>
		<td>
			<% if game.spread.nil? %>
				<%= game.moneyline_away %><br />
				<%= game.moneyline_home %>
			<% else %>
				<%= -game.spread %><br />
				<%= game.spread %>
			<% end %>
		</td>
		<td>
			<%= game.total_points %>
		</td>
		<% if current_user %>
		<td>
			<a href="<%= new_event_bet_path(game.id) %>" class="wager_link_home button black_gradient">Pick</a>
		</td>
		<% end %>
	</tr>
	<% end %>
<% else %>
	<tr style="height:100px;"><th>There are no games to show for your selected sport</th></tr>
<% end %>
</table>
<span id="confirm_place_bet"><div></div></span>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sport %><br />
    <%= f.number_field :sport %>
  </div>
  <div class="field">
    <%= f.label :spread %><br />
    <%= f.text_field :spread %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :isLive %><br />
    <%= f.check_box :isLive %>
  </div>
  <div class="field">
    <%= f.label :home %><br />
    <%= f.text_field :home %>
  </div>
  <div class="field">
    <%= f.label :away %><br />
    <%= f.text_field :away %>
  </div>
  <div class="field">
    <%= f.label :extern_id %><br />
    <%= f.text_field :extern_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_game_list.html.erb
<table id="featured_games_table">
<% if games.length > 0 %>	
	<% games.each do |game| %>
	<% if sport != game.sport %>
	<tr>
		<td style="border:none !important; margin-top:20px;position: relative; display: block;"><h2><%= LEAGUE_NAMES_ABBR[game.sport-1] %> Games</h2></td>
		<% sport = game.sport %>
	</tr>
	<tr>
		<th>Start Time</th>
		<th>Matchup</th>
		<% if game.sport == 3 %>
		<th>Moneyline</th>
		<% else%>
		<th>Handicap</th>
		<% end %>
		<th>Total Points</th>
		<th></th>
	</tr>
	<% end %>
	<tr>
		<td>
			<span style="font-weight:bold"><%= game.start_time.strftime("%I:%M%P").upcase %></span><br />
			<%= game.start_time.strftime("%m-%d") %>
		</td>
		<td>
			<span class="featured_team_name"><%= game.away_team %>@</span><br/> <span class="featured_team_name"><%= game.home_team %></span>
		</td>
		<td>
			<% if !game.spread.nil? %>
				<%= -game.spread %><br />
				<%= game.spread %>
			<% else %>
				<%= game.moneyline_home %><br />
				<%= game.moneyline_away %>				
			<% end %>
		</td>
		<td>
			over <%= game.total_points %><br />
			under <%= game.total_points %>
		</td>
		<% if current_user %>
		<td>
			<a href="<%= new_event_bet_path(game.id) %>" class="wager_link_home button black_gradient">Pick</a>
		</td>
		<% end %>
	</tr>
	<% end %>
<% else %>
	<tr><th>There are no games today for your selected sport</th></tr>
<% end %>
</table>
<span id="confirm_place_bet"><div></div></span>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/featured_games.js.erb
$("#featured_games_table").html($("<%= escape_javascript(render :partial => 'events/featured_games', :locals => {:featured => @featured}) %>"));
$("#selected_sport").text("<%= @selected_sport %>");

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Sport</th>
    <th>Spread</th>
    <th>Start time</th>
    <th>Islive</th>
    <th>Home</th>
    <th>Away</th>
    <th>Extern</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.sport %></td>
    <td><%= event.spread %></td>
    <td><%= event.start_time %></td>
    <td><%= event.isLive %></td>
    <td><%= event.home %></td>
    <td><%= event.away %></td>
    <td><%= event.extern_id %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1><%= @event.away_team %> @ <%= @event.home_team %></h1>