config/routes.rb
PickingDucks::Application.routes.draw do
  resources :sessions
  resources :events
  resources :bets 
  resources :users 
  resources :events do
    resources :bets
  end
  resources :password_resets
  resources :cashouts
  
  get "/how_to_play" => "application#how_to_play", :as => "how_to_play"
  get "/privacy" => "application#privacy", :as => "privacy"
  get "/terms_of_service" => "application#terms_of_service", :as => "terms_of_service"
  get "/about_us" => "application#about_us", :as => "about_us"
  
  get 'public_profile/:id' => "users#public_profile", :as => "public_profile"
  get 'pay_for_bet/:user_id/:bet_id' => "users#pay_for_bet", :as => "pay_for_bet"
  get 'pay_money_for_bet/:user_id/:bet_id' => "users#pay_money_for_bet", :as => "pay_money_for_bet"
  
  get "/sport/:sport_id" => "sports#sport_home", :as => "sport_home"
  
  get "/bets_home" => "bets#bets_home", :as => "bets_home"
  get "/make_parlay" => "bets#make_parlay", :as => "make_parlay"
  get "/request_cashout" => "users#request_cashout", :as => "request_cashout"
  get "/get_bets_for_date" => "users#get_bets_for_date", :as => "get_bets_for_date"
  get '/calc_payout/:event_id/:amount/:pick' => "bets#calc_payout", :as => "calc_payout"
  get '/reset_ducks' => 'users#reset_ducks', :as => "reset_ducks"
  post "/add_bets_to_parlay" => "bets#add_bets_to_parlay", :as => "add_bets_to_parlay"
  post '/make_bet_private/:id' => "bets#make_bet_private", :as => "make_bet_private"
  post '/buy_ducks' => "users#buy_duck", :as => "buy_ducks"
  post '/buy_bet_info' => "users#buy_bet_info", :as => "buy_bet_info"
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "user#new", :as => "sign_up"
  get "get_featured" => "home#get_featured", :as => "get_featured"
  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picking Ducks</title>  
  <%= favicon_link_tag 'favicon.ico' %>
  
  
  <%= javascript_include_tag 'https://js.stripe.com/v1/' %>
  <%= javascript_include_tag "application" %>  
  
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
</head>
<body>	
	<header class="main header" id="top">
		<div class="container user-nav">
			<% if current_user %>
				<span style="color:white">
					Logged in as <a style="text-decoartion:underline" href="<%= user_path(current_user.id) %>"><%= current_user.email %></a>
					<%= link_to_function "<span class='logout_link' style='text-align:center'>Log out</span>".html_safe, "logout()" %>								
				</span>
				
			<% else %>
				<%= link_to_function "Register", "show_sign_up()", :class => "login_link" %> 
				<%= link_to_function "Log in", "show_log_in()", :class => "login_link" %>
			<% end %>
		</div>
	</header>
	<div class="container sports">
		<div class="container top-banner">

			<div class="container page-section">
			<a href="/" class="logo"><%= image_tag asset_path "pd-logo.png", :alt=>"Picking Duck- Your Sports Pick Marketplace" %></a>


			
			</div> <!-- end page section -->

		</div> <!-- end top banner -->
		
		<div class="nav">
			<ul class="site-nav">
				<a href="/"><li>HOME</li></a>
				<a href="<%= users_path %>"><li>PLAYER SEARCH</li></a>
				<a href="<">
				<% if current_user %>
					<a href="<%= user_path current_user %>"><li>MY PROFILE</li></a>
					<a href="<%= bets_home_path %>"><li>MAKE PICKS</li></a>
				<% end %>
				<a href="<%= sport_home_path(1) %>"><li>NFL</li></a>
				<a href="<%= sport_home_path(2) %>"><li>NBA</li></a>
				<a href="<%= sport_home_path(3) %>"><li>MLB</li></a>
				<a href="<%= sport_home_path(4) %>"><li>NHL</li></a>
				<a href="<%= how_to_play_path %>"><li>How to play</li></a>
			</ul>
		</div>
		<% if flash.keys.length > 0 %>
			<div id="flash_messages" style="padding-top:10px">	
				<% flash.each do |name, msg| %>
				 <%= content_tag :div, msg.html_safe, :class => "flash_#{name}" %>
				<% end %>
			</div>
			<% else %>
			<% end %>
		<% if !current_user %>
			
				<%= render :template => 'users/new', :locals => { :user => User.new } %>
			
				<%= render :template => 'sessions/new'%>
		<% end %>
		<div class="container main-content">	
			<div id="content">
			<%= yield %>			
			</div>
			<footer>
				<ul id="nav">
					<li><a href="/about_us" title="">About Us</a></li>
			        <li><a href="" title="">Contact Us</a></li>
			        <li><a href="/terms_of_service" title="">Terms of Service</a></li>
					<li><a href="/privacy" title="">Privacy</a></li>
					<li><a class="active" href="" title="">RSS</a></li>
			        <li><a class="right" href="" title="">&copy; 2013 Picking Ducks</a></li>
			    </ul>
			</footer>
		</div>
	</div>
</body>
</html>